# Generated by Django 4.0.5 on 2022-06-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_bunka_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunka',
            old_name='name',
            new_name='名称',
        ),
    ]
