# Generated by Django 4.0.5 on 2022-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_url_bunka_url_rename_juusyo_bunka_愛媛県松山市住所_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunka',
            name='単位',
            field=models.CharField(default='一次的', max_length=20, verbose_name='単位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bunka',
            name='数',
            field=models.CharField(default=1, max_length=20, verbose_name='数'),
            preserve_default=False,
        ),
    ]
